export const READ_ALARM_LIST = "READ_ALARM_LIST";
export const READ_LIST_FAILURE = "READ_LIST_FAILURE";
export const UPDATE_ALARM = "UPDATE_ALARM";
export const UPDATE_ALARM_FAILURE = "UPDATE_ALARM_FAILURE";
